import type { LocalAutoTraderVehicle } from "@/lib/integrations/autotrader/mapping";

export function validAutoTraderVehicle(
  changes: Partial<LocalAutoTraderVehicle> = {},
): LocalAutoTraderVehicle {
  return {
    id: "11111111-1111-4111-8111-111111111111",
    organisationId: "22222222-2222-4222-8222-222222222222",
    registration: "AB12 CDE",
    vin: "WVWZZZ1JZXW000001",
    stockNumber: "STOCK-001",
    make: "Volkswagen",
    model: "Golf",
    derivative: "1.5 TSI Life 5dr",
    trim: "Life",
    bodyType: "Hatchback",
    fuelType: "Petrol",
    transmission: "Manual",
    colour: "Blue",
    doors: 5,
    seats: 5,
    engineSizeCc: 1498,
    powerBhp: 148,
    co2EmissionsGKm: 122,
    euroEmissionsStandard: "EU6",
    year: 2022,
    firstRegistrationDate: "2022-06-01",
    motExpiry: "2027-06-01",
    previousOwners: 1,
    mileage: 20_000,
    serviceHistory: "Full service history",
    keys: 2,
    retailPrice: 15_995,
    actualSalePrice: null,
    soldAt: null,
    attentionGrabber: "Excellent condition",
    description: "A well maintained vehicle.",
    standardEquipment: ["Air conditioning", "Bluetooth"],
    optionalEquipment: ["Winter pack"],
    features: [],
    videoUrl: "https://www.youtube.com/watch?v=placeholder",
    interiorColour: "Black",
    interiorMaterial: "Cloth",
    fuelConsumptionUrbanMpg: 42,
    fuelConsumptionExtraUrbanMpg: 58,
    fuelConsumptionCombinedMpg: 51,
    wheelchairAccessible: false,
    acceleration060Seconds: 8.5,
    topSpeedMph: 130,
    engineNumber: null,
    cylinderCount: 4,
    driveType: "Front Wheel Drive",
    grossWeightKg: 1_900,
    lengthMm: 4_284,
    widthMm: 1_789,
    plate: "22",
    advertisedCondition: "used",
    status: "on_forecourt",
    deletedAt: null,
    autotraderStockId: null,
    channel: {
      status: "ready",
      externalStockId: null,
      externalDerivativeId: "test-derivative-placeholder",
      metadata: {},
    },
    ...changes,
  };
}
